[package]
name = "unid"
version = "0.1.0"
authors = [ "UNiD <>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cipher_lib"
path = "src/lib.rs"
crate-type = [ "cdylib" ]

[dependencies]
aes = "0.7.4"
block-modes = "0.8.1"
hex-literal = "0.3.3"
hex = "0.4.3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
rand = "0.8.4"
base64 = "0.13.0"
bytebuffer = "0.2.1"
getrandom = { version = "0.2", features = [ "js" ] }
scrypt = "0.7.0"

[dependencies.wasm-bindgen]
version = "0.2.76"
features = [ "serde-serialize" ]
