name: Rust (Build & Unit Test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: (config) set nightly toolchain to default
      run: rustup default nightly
    - name: (install) llvm-tools-preview
      run: rustup component add llvm-tools-preview
    - name: (install) rust-src
      run: rustup component add rust-src
    - name: (install) grcov
      run: cargo install grcov
    - name: (run) build
      run: make build
    - name: (run) tests
      run: make test
      env:
        RUSTFLAGS: -Zinstrument-coverage
        LLVM_PROFILE_FILE: profraw/llvm-%p-%m.profraw
    - name: (run) coverage
      run: grcov . --source-dir . --binary-path target/debug --output-type lcov --branch --ignore-not-existing --output-path coverage
      env:
        LLVM_PROFILE_FILE: profraw/llvm-%p-%m.profraw
    - name: (run) upload to coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage
