name: Rust (Build & Unit Test)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - name: set nightly toolchain to default
      run: rustup default nightly
    - name: add rust-src to component
      run: rustup component add rust-src
    - name: run build
      run: make build
    - name: run tests
      run: make test
